name: Update Strava Stats Joel

on:
  schedule:
    - cron: '0 1 * * *' # Elke nacht om 01:00
  workflow_dispatch: # Zodat je het ook handmatig kunt starten

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Strava Update Script
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: python update_activities.py

      - name: Run Dashboard Generator
        run: python maak_dashboard.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Voeg zowel het logboek als het dashboard toe
          git add activities.csv dashboard.html
          # Alleen opslaan als er echt iets veranderd is
          git commit -m "Robot: Data en Dashboard bijgewerkt voor JoÃ«l" || exit 0
          git push
